### ISSUE TITLE
VSC extension: automated checks for assignment requirements

### ISSUE THREAD

**Issue by chauff** [chauff/cse1500-web-transcripts#99]
Ideal scenario: students download a VSC extension that checks for basic assignment requirements (use of certain CSS constructs, JS design patterns, etc.)

**Comment by radostefanov** [comment]
A possible option would be to use ESLint, as it's one of the most used static code analysis tools. VS Code has also an extension for ESLint, which highlights all issues reported from ESLint (screenshot below). A config file can be created in order to match the assignment requirements.

<img width="500" alt="Screenshot 2019-10-22 at 21 46 58" src="https://user-images.githubusercontent.com/12081080/67333330-a8b98580-f520-11e9-8d2f-fbc3f95d6e27.png">

**Comment by chauff** [comment]
Thanks, I'll see if I can do that! If that would work, it would be an easy solution.

**Comment by chauff** [comment]
Dropped for now. Much more time needed.
